
- hosts: webserver
  # in ansible the tasks can be executed a different user by using become plugin
  become: true
  become_user: root
  tasks:
  - name: update apt-cache
    apt: update_cache=yes cache_valid_time=3600
  - name: install package for LAMP architecture
    package: name={{item}} state=present
    loop:
     - apache2
     - mysql-server
     - php-mysql
     - php
     - libapache2-mod-php
     - python3-mysqldb

