
---
- hosts: webserver
  tasks:
  - name: Execute a command on the host
    command: hostname -s
    # register in ansible is used to save output of the command in a variable
    register: hostname_output
  - name: Show the ouput value
    debug:
     var: hostname_output.stdout
