

# tasks file for tomcat


---
# tasks file for tomcat

- name: config users
  include_tasks: configure-user.yml
  when: action == "install"

- name: install java
  include_tasks: install-java.yml
  when: action == "install"

- name: install tomcat
  include_tasks: install-tomcat.yml
  when: action == "install"

- name: uninstall tomcat
  include_tasks: uninstall-tomcat.yml
  when: action == "uninstall"
